version: "3.8"

services:
  churn-model:
    build: .
    volumes:
      - ./data:/app/data
      - ./results:/app/results
    environment:
      - PYTHONUNBUFFERED=1
    command: ["python", "main.py"]
